version: "3.7"
services:
  angular:
    image: neileen/dockerhub_app:latest
    volumes:
      - ./angular:/app-angular
    ports:
      - "4200:4200"
  java:
    image: neileen/dockerhub_app:java-latest
    volumes:
      - ./java:/app-java
    ports:
      - "4201:4200"
