version: "3.7"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
#    volumes:
#      - type: bind
#        source: E:\Docker\DockerApp\elasticsearch
#        target: /elasticsearch
    networks:
      - elastic


  java-app:
    image: neileen/dockerhub_app:java-latest
    ports:
      - "8080:8080"
    depends_on:
      - es
    networks:
      - elastic


  angular-app:
    image: neileen/dockerhub_app:latest
    ports:
      - "4200:4200"
    networks:
      - elastic
    depends_on:
      - es


  python-app:
    image: neileen/dockerhub_app:python-latest
    ports:
      - "5002:5002"
    depends_on:
      - es
    networks:
      - elastic


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - type: bind
        source: E:\Docker\DockerApp\prometheus
        target: /prometheus
    command:
      - '--config.file=/prometheus/prometheus.yml'
    networks:
      - elastic


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"


networks:
  elastic:
    driver: bridge