version: "3.7"
services:
  java-app:
    image: neileen/dockerhub_app:java-latest
    ports:
<<<<<<< HEAD
      - "8080"
    # interactive mode used for java server to work
=======
      - "8080:8080"
>>>>>>> 2a06fcdf5f16766242d0a5df4038d03550d91ab5
    tty: true

  angular-app:
    image: neileen/dockerhub_app:latest
    ports:
      - "4200:4200"
    links:
      - java-app
      - python-app

  python-app:
    image: neileen/dockerhub_app:python-latest
    ports:
      - "5002:5002"