version: "3.7"
services:
  java-app:
    image: neileen/dockerhub_app:java-latest
    ports:
      - "8080:8080"
    depends_on:
      - es

  angular-app:
    image: neileen/dockerhub_app:latest
    ports:
      - "4200:4200"
    links:
      - java-app
      - python-app
    depends_on:
      - es

  python-app:
    image: neileen/dockerhub_app:python-latest
    ports:
      - "5002:5002"
    depends_on:
      - es
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.7
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - transport.tcp.port=9200
      - transport.publish_port=9200
      - client.transport.sniff=false
      - xpack.security.enabled=false
    ports:
      - "9201:9200"
      - "9300:9300"