version: "3.7"
services:
  java-app:
    image: neileen/dockerhub_app:java-latest
    ports:
      - "8080:8080"
    tty: true

  angular-app:
    image: neileen/dockerhub_app:latest
    ports:
      - "4200:4200"
    links:
      - java-app
      - python-app

  python-app:
    image: neileen/dockerhub_app:python-latest
    ports:
      - "5002:5002"