version: "3.7"
services:
  java:
    image: neileen/dockerhub_app:java-latest
    container_name: java_container
    volumes:
      - ./java:/app-java
    ports:
      - "8080:8080"

  angular:
    image: neileen/dockerhub_app:latest
    container_name: angular_container
    volumes:
      - ./angular:/app-angular
    ports:
      - "4200:4200"
    links:
      - java_container
	