version: "3.7"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic


  java-app:
    image: neileen/dockerhub_app:java-latest
    ports:
      - "8080:8080"
    depends_on:
      - es
    networks:
      - elastic


  angular-app:
    image: neileen/dockerhub_app:latest
    ports:
      - "4200:4200"
    networks:
      - elastic
    depends_on:
      - es


  python-app:
    image: neileen/dockerhub_app:python-latest
    ports:
      - "5002:5002"
    depends_on:
      - es
    networks:
      - elastic


networks:
  elastic:
    driver: bridge