{
 "title": "Docker Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Containers State",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers"
    }
   ]
  },
  {
   "title": "User and CPU time in seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])"
    }
   ]
  },
  {
   "title": "CPUs number",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus" }
   ]
  },
  {
   "title": "Bytes of memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes"
    }
   ]
  }
 ]
}